name: standard check

on:
    push:
        branches: [ "develop", "master" ]
    pull_request:
        branches: [ "develop", "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
    main:
        name: Nx Cloud - Main Job
        uses: ./.github/workflows/nx-cloud-main.yml
        secrets: inherit
        with:
            main-branch-name: develop
            number-of-agents: 2
            parallel-commands: |
                pnpm exec nx-cloud record -- pnpm exec nx format:check
            parallel-commands-on-agents: |
                pnpm exec nx run-many --target=lint --parallel=2 --all
                pnpm exec nx run-many --target=build --parallel=2 --all

    agents:
        name: Nx Cloud - Agents
        uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.6
        with:
            number-of-agents: 2
